### PR TITLE
Updated 'View Data' to better match 'Plan' and 'Waitlist' buttons

### PR DESCRIPTION
**Pull request by cameronellis**
- The background color of of "View Data" is now the same color as the "Plan" and "Waitlist" buttons
- When "View Data" is hovered over, the background-color turns white just like the "Plan" and "Waitlist" buttons
- The "View Data" button's border has been rounded to match the rounded border of the "Plan" and "Waitlist" buttons

### CODE REVIEW

**Comment by cameronellis** [comment]
The change looks like this

image

**Comment by j-delaney** [comment]
This is awesome! Could you also open a PR (feel free to just merge it in) to bump the patch version so I can upload this to the chrome webstore?

**Comment by cameronellis** [comment]
I believe that happened? I'm not sure. Apologies

**Comment by j-delaney** [comment]
I don't think so. I'm only seeing "Files Changed" as 1. Maybe you did the change locally but it didn't get added to the commit?

**Comment by cameronellis** [comment]
Oh, I understand what you mean now. I can do that. I'll update the change log file

**Pull request merged**
